spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ssgdb
    username: ssg_user
    password:
    sql-script-encoding: utf-8

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true

  http:
    encoding:
      charset: UTF-8
      enabled: true

server:
  port: 5555
 
