DROP TABLE IF EXISTS PUBLIC.COFFEE;
DROP TABLE IF EXISTS PUBLIC.CAFE;
DROP TABLE IF EXISTS PUBLIC.MENU;
CREATE TABLE PUBLIC.COFFEE(COFFEE_ID BIGINT NOT NULL PRIMARY KEY,COFFEE_NAME VARCHAR(255));
CREATE TABLE PUBLIC.CAFE(CAFE_ID BIGINT NOT NULL PRIMARY KEY,CAFE_NAME VARCHAR(255));
CREATE TABLE PUBLIC.MENU(CAFE_ID BIGINT NOT NULL,COFFEE_ID BIGINT NOT NULL,PRIMARY KEY(CAFE_ID,COFFEE_ID),CONSTRAINT FKJJV0YQKTKRNPMWRN9BLOHDT8F FOREIGN KEY(CAFE_ID) REFERENCES PUBLIC.CAFE(CAFE_ID),CONSTRAINT FKOGI80SUBFUX6G6NCIK1MTYN88 FOREIGN KEY(COFFEE_ID) REFERENCES PUBLIC.COFFEE(COFFEE_ID));
